### ISSUE TITLE
feature idea: Add in nvidia driver install

### ISSUE THREAD

**Issue by danny-kirby** [aws-samples/amazon-ec2-nice-dcv-samples#1]
A nice to have would be adding in logic for installing nvidia drivers for g4 or g5 instance type family on the cf scripts

**Comment by limmike** [comment]
Thanks for the suggestion. As per [Install NVIDIA drivers on Windows instances](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html) and [Install NVIDIA drivers on Linux instances ](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html), users have the option to install Tesla, GRID or gaming drivers. Installation and configuration is different for each driver type, instance type and OS, and driver files are few hundred MB in size.  

Let me explore enhancing cfn to include a helper script file in the EC2 that users can use to download drivers, and decide for themselves which driver to install.  Alternatively, nVidia and AWS offers AMIs with NVIDIA drivers installed, e.g. [gaming drivers](http://aws.amazon.com/marketplace/search/results?searchTerms=NVIDIA+gaming), [Tesla driver](http://aws.amazon.com/marketplace/search/results?page=1&filters=VendorId&VendorId=e6a5002c-6dd0-4d1e-8196-0a1d1857229b%2Cc568fe05-e33b-411c-b0ab-047218431da9&searchTerms=tesla+driver), and [GRID driver.](http://aws.amazon.com/marketplace/search/results?&searchTerms=NVIDIA+quadro). You can use [user data scripts](https://github.com/aws-samples/amazon-ec2-nice-dcv-samples/tree/main/scripts) to install NICE DCV while launching them.

**Comment by limmike** [comment]
I have updated CfN templates to include helper script to download NVIDIA GRID and gaming and AMD GPU drivers, and configure the server as per [Install NVIDIA drivers on Windows instances](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html). Please refer to [Prerequisites for Windows NICE DCV server on Amazon EC2 instances](https://docs.aws.amazon.com/dcv/latest/adminguide/setting-up-installing-winprereq.html) for driver installation and configuration instructions.

**Comment by limmike** [comment]
Updated Windows template with option to specify GPU driver to install. Tested with g4dn and g4ad instance types.
