### ISSUE TITLE
VPC and Subnet - part of CloudFormation stacks

### ISSUE THREAD

**Issue by ruzickap** [aws-samples/amazon-ec2-nice-dcv-samples#3]
Hello

Wouldn't it make sense to have some "default" VPC and Subnet part of the CloudFormation templates?

Ideally end users should these templates as "easy to go" solution without creating the VPC/Subnet in advance.

Thank you for a great work...

**Comment by limmike** [comment]
Hello

When users start using AWS, they have a [default VPC](https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html) in each region. The default VPC comes with a public subnet in each AZ, an internet gateway, and settings to enable DNS resolution. There is no need to create VPC and subnet in advance.

Users can select default VPC and subnet in the CloudFormation parameters page, and use default settings for the rest. They do need to create EC2 key pair (for Linux), and I have included link ([https://console.aws.amazon.com/ec2/#KeyPairs](https://console.aws.amazon.com/ec2/#KeyPairs)) in parameter description for user convenience. 
User can also use AWS CLI from CloudShell to get the values,

```
aws ec2 describe-vpcs --query "Vpcs[*].VpcId"
aws ec2 describe-subnets --query 'Subnets[*].[SubnetId,VpcId]' 
```

Thanks for the feedback!
