### ISSUE TITLE
KaliLinux-NICE-DCV CloudFormation CREATE_FAILED

### ISSUE THREAD

**Issue by ruzickap** [aws-samples/amazon-ec2-nice-dcv-samples#6]
It seems like there is some problem with latest version of `KaliLinux-NICE-DCV.yaml`.
When trying to deploy the CF template I got Status `CREATE_FAILED`.

Maybe error in `/var/log/cloud-init-output.log`:

```console
...
Setting up nice-dcv-server (2023.1.16388-1) ...
Creating GDM greeter script '/usr/share/gdm/greeter/autostart/dcv.desktop'...
Creating GDM script '/usr/lib/x86_64-linux-gnu/dcv/dcvgdm'...
WARNING: display-setup-script is already defined in /etc/lightdm/lightdm.conf, it will override the setting in /etc/lightdm/lightdm.conf.d/50-dcvxgrantaccess.conf
Adding DCV specific customizations to '/usr/lib/x86_64-linux-gnu/dcv/dcvgdm' script...
Removing DCV specific customizations from '/usr/lib/x86_64-linux-gnu/dcv/dcvgdm' script...
No changes were done
Adding DCV specific customizations to '/usr/lib/x86_64-linux-gnu/dcv/dcvlightdm' script...
No changes were done
Removing DCV specific customizations from '/usr/lib/x86_64-linux-gnu/dcv/dcvlightdm' script...
No changes were done
/usr/lib/x86_64-linux-gnu/dcv/dcv: symbol lookup error: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined symbol: g_once_init_leave_pointer
dpkg: error processing package nice-dcv-server (--configure):
 installed nice-dcv-server package post-installation script subprocess returned error exit status 127
Setting up libfuse2t64:amd64 (2.9.9-8.1) ...
Setting up mount-s3 (1.6.0) ...
Processing triggers for libc-bin (2.38-10) ...
Processing triggers for kali-menu (2023.4.7) ...
Errors were encountered while processing:
 nice-dcv-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
...
```

Not sure...

Thanks for looking at it...

**Comment by limmike** [comment]
Thanks for reporting. This is an error installing nice-dcv-server package as per `cloud-init-output.log`

```
/usr/lib/x86_64-linux-gnu/dcv/dcv: symbol lookup error: /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0: undefined symbol:
g_once_init_leave_pointer
dpkg: error processing package nice-dcv-server (--configure):
 installed nice-dcv-server package post-installation script subprocess returned error exit status 127
Processing triggers for libc-bin (2.38-10) ...
....
Errors were encountered while processing:
 nice-dcv-server
```
There is a conflict with ` libgdk-pixbuf-2.0-0` which is part of [`gdk-pixbuf`](https://pkg.kali.org/pkg/gdk-pixbuf) by `libc-bin` which is part of [`glibc`](https://pkg.kali.org/pkg/glibc). From what I can tell, `gdk-pixbuf` was updated this week [20th May](https://pkg.kali.org/news/587295/gdk-pixbuf-24212dfsg-1-imported-into-kali-rolling/) while `glibc` was updated last week [15th May](https://pkg.kali.org/news/584525/glibc-238-10-imported-into-kali-rolling/)

As stated on [cfn\README.md](https://github.com/aws-samples/amazon-ec2-nice-dcv-samples/blob/main/cfn/README.md), Kali Linux is _not supported_ by NICE DCV and may not work.  Kali Linux is a [rolling release](https://www.kali.org/blog/kali-linux-2016-1-release/), where there is a continuous stream of updates.  While we may get it to work with older packages, this may break other applications. Perhaps a newer update may resolve this.

**Comment by ruzickap** [comment]
Make sense...

Thank you for a nice description :-)
